### PR TITLE
Enable macOS build

### LINKED ISSUE #2: Build on macOS
Looks like it is possible to build this on macOS. Would be nice to have a macOS build of it.

ref: http://portaudio.com/docs/v19-doxydocs/compile_mac_coreaudio.html

### PR DESCRIPTION
**Pull request by traversaro**
I incorporated the script from https://github.com/AnacondaRecipes/portaudio-feedstock and added a patch to disable `-Werror` on macOS.

Fix https://github.com/conda-forge/portaudio-feedstock/issues/2 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
> 
> 
> Hi! This is the friendly automated conda-forge-linting service.
> 
> I just wanted to let you know that I linted all conda-recipes in your PR (`recipe`) and found it was in an excellent condition.
> 
> I do have some suggestions for making it better though...
> 
> For **recipe**:
> 
>     * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.
> 
> 
> Documentation on acceptable licenses can be found [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions).

Fixed by switching to MIT, as per PortAudio website (http://www.portaudio.com/license.html) "In terms of legal compatibility, the PortAudio licence is now a plain MIT licence" .

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge/portaudio this PR should be ready for review. If you want, I will be also happy to add myself as a maintainer.

**Comment by jakirkham** [comment]
Thanks for adding this Silvio! 😄

**Pull request merged**
